version: '3.1'
networks:
  proxy:
    external: true
services:
  mysql:
    container_name: api-platform-mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - proxy
  phpmyadmin:
    container_name: api-platform-phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql
    ports:
      - 8082:80
    networks:
      - proxy
    labels:
      - "traefik.frontend.rule=Host:phpmyadmin-api-platform.docker.localhost"
  httpd:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/dockerfile/Dockerfile.httpd-fpm
    container_name: api-platform-httpd
    volumes:
      - ./docker/resources/000-default.conf:/etc/apache2/sites-available/000-default.conf:ro
      - .:/var/www/html/current:ro
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    depends_on:
      - php
    ports:
      - 8070:80
    networks:
      - proxy
    labels:
      - "traefik.frontend.rule=Host:sf4-api-platform.docker.localhost"
  php:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/dockerfile/Dockerfile.php-fpm71
    container_name: api-platform-php7
    volumes:
      - ./:/var/www/html/current
      - ./docker/resources/php.ini:/usr/local/etc/php/php.ini:ro
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    depends_on:
      - mysql
    networks:
      - proxy